"""CompileGate: compile a project and drive fixer/test-repair on failures."""

from dataclasses import dataclass
from pathlib import Path

from squeaky_clean.application.dtos.compile_result import CompileResult
from squeaky_clean.application.dtos.fix_request import FixRequest
from squeaky_clean.application.dtos.language_toolkit import LanguageToolkit
from squeaky_clean.application.dtos.module_implementation import ModuleImplementation
from squeaky_clean.application.dtos.test_run_result import TestRunResult
from squeaky_clean.application.use_cases.fixer_stage import (
    FixerStage,
    FixerStageResult,
)
from squeaky_clean.application.use_cases.repair_test_file import (
    RepairTestFile,
    TestRepairRequest,
)
from squeaky_clean.domain.entities.architecture_spec import ArchitectureSpec
from squeaky_clean.domain.interfaces.project_compiler import ProjectCompiler


@dataclass(frozen=True)
class CompileGateRequest:
    """Inputs to one CompileGate run."""

    implementation: ModuleImplementation
    output_dir: Path
    max_passes: int
    architecture: ArchitectureSpec | None = None
    toolkit: LanguageToolkit | None = None


@dataclass(frozen=True)
class CompileGateResult:
    """Outcome: residual compile-error count + aggregated fixer usage."""

    compile_errors: int
    fixer: FixerStageResult


class CompileGate:
    """Compile before tests; on failure fix source classes AND repair tests.

    A no-op (zero errors) when no compiler is wired for the language, so
    dynamically-typed targets simply skip the gate. Source classes are
    regenerated by the fixer; test files that assume the wrong signatures
    are regenerated against the real source by ``test_repairer``.
    """

    def __init__(
        self, compiler: ProjectCompiler | None, fixer_stage: FixerStage,
        test_repairer: RepairTestFile | None = None,
    ) -> None:
        self._compiler: ProjectCompiler | None = compiler
        self._fixer: FixerStage = fixer_stage
        self._repairer: RepairTestFile | None = test_repairer

    def run(self, request: CompileGateRequest) -> CompileGateResult:
        """Compile, then fix source + repair tests up to ``max_passes``."""
        if self._compiler is None:
            return CompileGateResult(0, self._empty())
        agg = self._empty()
        result = self._compiler.compile(request.output_dir)
        for _ in range(max(0, request.max_passes)):
            if result.ok:
                break
            acted, agg = self._one_pass(request, result, agg)
            if not acted:
                break
            result = self._compiler.compile(request.output_dir)
        return CompileGateResult(result.error_count, agg)

    def _one_pass(
        self, request: CompileGateRequest, result: CompileResult,
        agg: FixerStageResult,
    ) -> tuple[bool, FixerStageResult]:
        acted = False
        if result.offending_stems:
            stats = self._fixer.apply(
                self._fix_request(request, result), request.output_dir)
            agg = agg.merge(stats)
            acted = acted or stats.classes_fixed > 0
        if result.test_files and self._can_repair(request):
            stats = self._repair_tests(request, result)
            agg = agg.merge(stats)
            acted = acted or stats.classes_fixed > 0
        return acted, agg

    def _can_repair(self, request: CompileGateRequest) -> bool:
        return self._repairer is not None and request.toolkit is not None

    def _repair_tests(
        self, request: CompileGateRequest, result: CompileResult,
    ) -> FixerStageResult:
        repairer = self._repairer
        toolkit = request.toolkit
        if repairer is None or toolkit is None:
            return self._empty()
        n = 0
        cost = 0.0
        toks_in = toks_out = dur = 0
        for rel in result.test_files:
            resp = repairer.repair(TestRepairRequest(
                request.output_dir, rel, result.raw_output, toolkit))
            if resp is None:
                continue
            n += 1
            cost += resp.cost_usd
            toks_in += resp.input_tokens
            toks_out += resp.output_tokens
            dur += resp.duration_ms
        return FixerStageResult(n, toks_in, toks_out, cost, dur, 1 if n else 0)

    @staticmethod
    def _empty() -> FixerStageResult:
        return FixerStageResult(0, 0, 0, 0.0, 0, 0)

    @staticmethod
    def _fix_request(
        request: CompileGateRequest, result: CompileResult,
    ) -> FixRequest:
        return FixRequest(
            implementation=request.implementation,
            test_run_result=TestRunResult(
                0, result.error_count, 0, 0, result.raw_output),
            override_stems=result.offending_stems,
            architecture=request.architecture,
        )
